# Generated by Django 5.1 on 2024-09-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
