# Generated by Django 5.1 on 2024-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creelo_app', '0002_productimage_added_by_productimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_link',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
