# Generated by Django 5.1 on 2025-01-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creelo_app', '0005_product_is_instock_product_rating_product_reviews_and_more'),
        ('master_config', '0002_category_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='master_config.category'),
        ),
    ]
